### ISSUE TITLE
Don't run the EnvironmentLoader twice. "If you want to open the HBL, launch the Mii Maker instead"

### ISSUE THREAD

**Issue by PEEK-EZ** [V10lator/NUSspli#205]
Hello, I'm new to Homebrew Wii U. I downloaded the latest Version of NUSspli (v1.131) and I've been trying for hours to get it to launch on the HBL. I am using Tiramisu, but I don't know how to check what version of Tiramisu I'm on. I was hoping you could help me fix this issue. 

Extra info:

* I have formatted my SD card to FAT32
* I am using Tiramisu (Not sure if it's the latest ver)
* NUSSpli does show up in the Mii maker rooted HBL but once I click on it 3 seconds later it says the following, ("Don't run the EnvironmentLoader twice. If you want to open the HBL, launch the Mii Maker instead")
* I have double checked that the Latest uncompressed NUSspli (v1.31) folder is in the Wii U apps folder.

Other then that I have no clue on what to do and greatly appreciate it if you could help me out- Thank you!

**Comment by Monstermash28425R1** [comment]
Did you try the channel version? You can install it very easely with the WUT installer, i use a ftp server for file transfer and WUT installer to keep my nuspli updated

**Comment by Monstermash28425R1** [comment]
For you problem, that error shows up when you run the Jack (tiramisu loader) twice, you should check your tiramisu, hbl and nuspli versions and compatilibility

**Comment by PEEK-EZ** [comment]
I have not tried the channel version yet, that sounds like a good idea. I have some questions though, let's say that my HBL isn't the latest one, would it be age to delete it and install a different version? And my second question is how do I check the compatibility of tiramisu, hbl, and nuspli?

**Comment by PEEK-EZ** [comment]
I meant safe* not age

**Comment by V10lator** [comment]
1) Please use the edit function instead of double-posting. That way it's more simple to follow for the devs.
2) This is not a place to ask for support. Use either https://discord.com/invite/B8ZBd6mrnV or https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/ for such questions, please.
3) To update Tiramisu redownload the files from https://tiramisu.foryour.cafe and put them on the SD card overwriting existing ones. HBL (in Mii Maker) is part of Tiramisu, so don't worry about that.
