### ISSUE TITLE
"Keep downloaded files"  option greyed out (locked to no) when installing

### ISSUE THREAD

**Issue by al-gh** [V10lator/NUSspli#228]
The "keep downloaded files" option is unchangeable for for me when installing a title. Being able to keep the files would be great so that we wouldn't have to re-download the whole thing if the installation fails.

**Comment by V10lator** [comment]
That's possible for SD dowloads only as MCP (the tool from Nintendo doing the actual installation) deletes the files on the fly while installing.

Still keeping this report open as I have an idea since some time, it might just not work... So will try that soon and after that close this with either done or can't do.

**Comment by V10lator** [comment]
Tried it and sadly it doesn't work, sorry.
