### ISSUE TITLE
Title browser: Add filters/tabs

### ISSUE THREAD

**Issue by Roet-Ivar** [V10lator/NUSspli#29]
A side pop-up side menu with search and list filters would be a natural next step when core functionality is in good shape.

The filter menu could handle stuff like:
- Region: EU / JP / US
- Sort by: Title / Size / Rel. date / Installed status / other meta data
- Type: Game / DLC / App / Demo

**Comment by V10lator** [comment]
Which sounds like a simple task is actually a hard one. This is caused by how NUSspli handles the title database internally: There's a server (http://napi.nbg01.v10lator.de/titles.php) which serves the database. Now the problem is this serving looks like that:
```
{
	"2": {
		"000100":["boot1","ALL"],
		"000200":["DRH firmware","ALL"],
		"000400":["Bluetooth firmware","ALL"]
	},
	"3":{
		"042300":["Contains exceptions.txt file","ALL"],
		"042400":["Fonts","ALL"],
		"04F000":["SWKBD (Software Keyboard) related","ALL"],
	},
	"4":{
		"010009":["HOME Menu (OSv9)","JPN"],
		"010109":["HOME Menu (OSv9)","USA"],
		"010209":["HOME Menu (OSv9)","EUR"],
	}
}
```
As you see title IDs have been reduced to a minimum. The upper 32 bit of the title ID have been completely replaced by a number between (inclusive) 0 and 7. From the lower 32 bit the first four bytes have been cutted off completely (as they are always 0x00). It has been designed that way to save traffic while serving the database and as this allows extremely fast title ID to game name lookups (which was the original purpose of this database. Doing it the other way around / seaching through it has been hacked on top later on). Sadly this means we're removing the information if the database entry is a game, update or DLC, for example. It also means larger search operations are slow.

Anyway, I'm slowly thinking about a version 2 for the online API which could solve these issues. The main reason for v2 was to transfair the region informations more efficient but bettering the API (by adding higher TID mappings from 0 to 9 instead of 0 to 7, so updates and DLCs can be distinguished) could be done in the same run.
