### ISSUE TITLE
Is it legal?

### ISSUE THREAD

**Issue by Boxiogral** [V10lator/NUSspli#31]
I want to know if it's legal before using it, because my ISP literally monitors every thing that i do and if they see anything illegal, they would call the cops and report the site owner and me.. so.. is it legal?

**Comment by Carlitosnu** [comment]
1. No, if the game is Legit because nothing they can do.
2. Other think is a direct download from Oficial Nintendo Servers. (They can think "is a direct download from Nintendo Eshop")

I hope help you (Sorry for the english is my 2nd language)

**Comment by E1ite007** [comment]
The app behaves the same way it would do if you where downloading from the eShop.
The packets it sends are similar from what the eShop sends since it downloads directly from Nintendo's NUS. So I doubt it would trigger your IPS, since if they saw it as something ilegal, then they would be triggering at Nintendo's servers, not any custom servers.

**Comment by V10lator** [comment]
This is for bug reports, not for legal support.
