### ISSUE TITLE
Installation Error on v1.152

### ISSUE THREAD

**Issue by DraconicDistress** [V10lator/NUSspli#332]
So to explain the problem, I recently homebrewed my Wii U and have been looking to load it up with games. The thing is, when trying to install games (in this specific case it was Pokken Tournament and Wonderful 101) I'm given an installation failed notif. No matter what I try, I can't get it to install.

The thing is, NUSspli has worked perfectly fine before, I already installed Wind Waker HD with no issue and can play it just fine. USB Sleep Mode is disabled, the Drive has been formatted directly on the Wii U, I haven't needed a Y/HDD cable so far (i don't actually know what they are or what they do) and as far as I'm aware there's nothing wrong with my system or the USB, so I don't know what I should do. 

My two main thoughts may be that either 1: I stopped the download before to move my console and that messed something up with the usb drive, or 2: because I formatted the USB on the Wii U directly, it just isn't working with the homebrew. Please help or tell me what's going on
![unnamed](https://github.com/user-attachments/assets/17625979-d597-4413-9fce-4004f8c8adac)

**Comment by V10lator** [comment]
> I already installed Wind Waker HD with no issue

As a VC game I guess it's mostly some (relative) big file (the ROM) and some metadata. Wii U games tend to have a lot more small files (textures, audio files and other stuff in the `content` folder). This might lead to more head movement (random writes instead of sequential writes) and as a result to more power draw. So the message might indeed be correct and this might be a power issue cause
> i don't actually know what they are or what they do

https://en.wikipedia.org/wiki/Y-cable#USB

In case this doesn't help you might want to try to install the very same titles with v1.151 to see it's really a bug in 1.152.

**Comment by DraconicDistress** [comment]
Hate to bother since this is closed but the problem is far from resolved. I have a Y-Cable now, and it's still not working, I still get the same error -_-what I can install is really iffy, like i installed Shovel Knight perfectly fine, but a game like Mario Maker or Affordable Space Adventure won't work at all so I have no clue what I'm doing wrong. should I reformat my usb? do i need to get a new one entirely? what can I do from here?
