### ISSUE TITLE
Speed-drop

### ISSUE THREAD

**Issue by ManCloud** [V10lator/NUSspli#36]
I've noticed that every "second" download limits itself to 2MB/s.
If NUSspli is restarted and the same download is started again, download speed is normal again (at approx. 10MB/s).
If the download looses connection and is resumed it occures as well.

Quite annoying 🙈

**Comment by SninkAran** [comment]
I have exactly the same issue, the worst thing is that although my internet is fast, it is also quite unstable and tends to crash constantly

**Comment by V10lator** [comment]
> I've noticed that every "second" download limits itself to 2MB/s.

Not sure what you mean with this. If you mean the speed decreasing every second for the blink of a second: That's caused by UI and download being on the same thread but UI being slowed down to 1 FPS. Bettering this is planned but with low priorit as we're already faster than the eShop.

> If the download looses connection and is resumed it occures as well.

Known issue most likely caused by desyncing of buffers and content on disc, meaning the buffers are no longer aligned to the SD/HDDs blocksize, resulting in slower write speeds. This fixes itsel after downloading the file in question (so the next file will be downloaded with fullspeed again) through, so it's low priority.

**Comment by ManCloud** [comment]
Scenario: I download game A... Game A loads at avg. 10Mb/s and finishes properly.

Now I want to download game B. Game B loads at avg. 2Mb/s. 

If I restart NUSspli also Game B loads at avg. 10Mb/s.

This does not heal by file progression but stays consistent for the whole download session.

Didn't try a third download in row yet.

**Comment by krisatjamf** [comment]
i've noticed the speed drop doesn't seem to correlate to files but runtime, when i try and download (games i already legit own), my download will start "fast" at around "8-10 Mb/s (1 MB/s)" and after 10-15 minutes drop down to around 180-300 KB/s and stay there for the duration.

i realize 10 Mb/s isn't fast but for my wii U on my internet thats the best i'm gonna get.

**Comment by krisatjamf** [comment]
> i've noticed the speed drop doesn't seem to correlate to files but runtime, when i try and download (games i already legit own), my download will start "fast" at around "8-10 Mb/s (1 MB/s)" and after 10-15 minutes drop down to around 180-300 KB/s and stay there for the duration.
> 
> i realize 10 Mb/s isn't fast but for my wii U on my internet thats the best i'm gonna get.

ok so, i received my lan adaptor today, which seems to have stabilzed my Wii's internet, i am also no longer experiencing the same dip in speed i've described above.  i'm wondering if the drop is due to a shaky internet connection.

i'm wondering if the Wii U's network stack is sensitive to either higher retransmit or high packet loss and is either adjusting on its own or those conditions are triggering some kind of bug in the network stack?
