### ISSUE TITLE
Wii u nusspli 

### ISSUE THREAD

**Issue by Noahg2011** [V10lator/NUSspli#360]
My autistic son has seen that he can access the Wii shop games with nusspli 

I’ve tried to download to a usb and it downloaded from my pc and looked ok but when plugged the usb into the Wii u it wanted formatting and deleted the application please help 
thx David

**Comment by V10lator** [comment]
This has nothing to do with NUSspli but with homebrews. You can't put homebrews on a FAT formatted USB drive but need an SD card (in the Wii Us card formatted at the front).

As I appreciate what you're doing here: You need a CFW (custom firmware) to run homebrew. Today we use Aroma for this. The guide to follow (please do not follow any other guide) is https://wiiu.hacks.guide . Maybe you could read that with your son, it's not as complicated as it sounds, then decide if you want to go into the world of homebrew / taking control over the hardware you own with your son. I'm not experienced with authism but maybe this might be a world he likes and you could go together with him. :)

Will close this as invalid now simply because CFW stuff is not directly related to NUSspli bugs but feel free to join our Discord in case you have any more questions or need some help in understanding that CFW stuff.

https://discord.gg/B8ZBd6mrnV

**Comment by Noahg2011** [comment]
> This has nothing to do with NUSspli but with homebrews. You can't put homebrews on a FAT formatted USB drive but need an SD card (in the Wii Us card slot located at the front).
> 
> As I appreciate what you're doing here: You need a CFW (custom firmware) to run homebrew. Today we use Aroma for this. The guide to follow (please do not follow any other guide) is https://wiiu.hacks.guide . Maybe you could read that with your son, it's not as complicated as it sounds, then decide if you want to go into the world of homebrew / taking control over the hardware you own with your son. I'm not experienced with authism but maybe this might be a world he likes and you could go together with him. :)
> 
> Will close this as invalid now simply because CFW stuff is not directly related to NUSspli bugs but feel free to join our Discord in case you have any more questions or need some help in understanding that CFW stuff.
> 
> https://discord.gg/B8ZBd6mrnV

Thanks for taking the time to reply I’ll try this thx again
