### ISSUE TITLE
Internal WUT in NUSspli error

### ISSUE THREAD

**Issue by Mattzuppp** [V10lator/NUSspli#363]
So you're saying this bug has no fucking solution???

**Comment by V10lator** [comment]
I say you're talking to the wrong person as this is a bug in WUT. I can't do anything, not even passing these bug reports forward as I am banned there.
Your language does not change these simple facts and you would know all this already if you would have looked at our bug tracker (the pinned bug at the top, really can't overlook it) right here.

Also is it really that hard to wait more than 10 hours? I have a live beside NUSspli, too, and am probably in a different timezone than you are.

I really have enough of your crybabies stealing my time instead of reading and acting accordingly cause again: I can't do anything. It's you users who have to make WUT developers aware!

So say goodbye to NUSspli support and say hello to WUT support: https://github.com/devkitPro/wut

**Comment by DiegoEshop** [comment]
@V10lator POSSIBLE RESOLUTION: Set to download only instead of install, and then just install it after it finishes downloading. Idk why but that worked for me :D

Still get an error occasionally (although, less often), but it doesn't crash anymore! So you can exit nusspli, go to settings, close settings, and go back to nusspli and the download will continue from where it left off.

--Someone on reddit said this, idk if work
