### ISSUE TITLE
Ecran rouge internet error Nusspli + info

### ISSUE THREAD

**Issue by Le-Ben-F** [V10lator/NUSspli#373]
Bonjour, j'ai bien vu le sujet "Erreur d’E/S mais je suis sur Internet et les applications qui nécessitent Internet fonctionnent bien" fermé par V10lator mais qui n'a pas vraiment eu de solution claire, je me permets donc…
Juste pour préciser, pour ma part j'ai comme sur la photo du sujet cité ci-dessus, un écran rouge avec le même message d'erreur au lancement de NussPli, cependant cela n'empêche en rien le téléchargement, il suffit d'appuyer sur b (revenir).
D'où ma question , pourquoi ce message d'erreur a chaque lancement, alors que dans les faits, cela n'est pas si pénalisant que cela?
2eme question, ma version de Nusspli est peut être vieille, si je prends la dernière version pour ma WiiU, cela changera t il quelque choses au catalogue de téléchargements disponible?

Merci Merci Merci d'avance pour vos réponses.

**Comment by V10lator** [comment]
English, please.

Yea, the issue is that WUT handles a WiFi error wrong, masking the real issue. Nobody ever said you can't just press (B) and continue, it's just that this bug report of you now ist invalid, too, as we can't get to the real root. Open a WUT bug report for this in case you want it fixed but do not continue to tell me about that!

Lastly ofc you should update, no support for outdated software!
