### ISSUE TITLE
Where will failed downloads be saved? (I downloaded it to my wii u's 32gb hard drive)

### ISSUE THREAD

**Issue by doanbachu** [V10lator/NUSspli#68]
**First of all i want to thank you so much for making a great app like nusspli but today i download and get error message at the end. I immediately checked my device space and it's still the same, (is it hidden or auto-removes?), Thanks <3**
_- Indeed nusspli is a great application, but maybe when downloading files> 2gb the success rate is only ~ 80%, hope you guys do better than this software_
**- Happy new year everyone**

**Comment by Masamune3210** [comment]
If I remember correctly, on error the app will clean up the damaged download

**Comment by V10lator** [comment]
Downloads should stay in the install folder (SD:/install, USB:/install or MLC:/install, depending on your setup).

NUSspli is not deleting files in case of errors but MCP might delete from USB or MLC, so Download to SD in case you want to make sure files stay).

Other than that this is not a place to ask questions but for bug reporst only. Will allow to keep this conversation now cause I want to mean what exactly you mean with
> when downloading files> 2gb the success rate is only ~ 80%

as neither beta testers nor me know about that (and we're downloading the largest files available regulary to ensure everything works as expected). So please explain some more and double check your USB drives power source as this might also be caused by a underpowered HDD.

**Comment by doanbachu** [comment]
> Downloads should stay in the install folder (SD:/install, USB:/install or MLC:/install, depending on your setup).
> 
> NUSspli is not deleting files in case of errors but MCP might delete from USB or MLC, so Download to SD in case you want to make sure files stay).
> 
> Other than that this is not a place to ask questions but for bug reporst only. Will allow to keep this conversation now cause I want to mean what exactly you mean with
> 
> > when downloading files> 2gb the success rate is only ~ 80%
> 
> as neither beta testers nor me know about that (and we're downloading the largest files available regulary to ensure everything works as expected). So please explain some more and double check your USB drives power source as this might also be caused by a underpowered HDD.

**Comment by doanbachu** [comment]
> Nếu tôi nhớ không nhầm, ứng dụng sẽ xóa bản tải xuống bị hỏng

oh thank you
