### ISSUE TITLE
update error related to WUP 

### ISSUE THREAD

**Issue by doanbachu** [V10lator/NUSspli#69]
**when updating to the last steps, the screen is red and the message appears (I forgot to take a picture) but related to WUP, indxiine's mocha startup is faulty (can't activate mocha but switch to Mii)**
-I re-hacked mocha and updated manually >successfully

**Comment by V10lator** [comment]
Please add the following informations in case you're able to recreate the issue:
* What version did you update from?
* HBL or Channel?
* Exact error message (I checked codes: There are 24 different red screens which could appear while updating. None of them are directly related to WUP through) ?

Other than that any reason to use Indexiine instead of Tiramisu? On your setup both, Indexiines Mocha and NUSspli exploit the IOSU which causes undefined behaviour (which might be what you mean with "faulty"). Tiramisu added new API calls to libiosuhax/WUPServer to grab the data we need, so no need to exploit IOSU anymore, so it's highly recommended to switch to Tiramisu.
To others reading this: Same double exploit issue is true for Haxchi (and CBHC). So it's recomended to switch, too.

**Comment by doanbachu** [comment]
oh thank you i will update the new hack right away, maybe the error comes from the old mocha hack like you said

**Comment by V10lator** [comment]
Closing this as last update was mainly for you to be able to recreate without needing to downgrade first but still no reply to the open quetions. So please reopen in case this is still an issue for you, else I'll just mark this as one more reaon for users to switch to Tiramisu.
