### ISSUE TITLE
mejoras para la tienda

### ISSUE THREAD

**Issue by luismyru** [V10lator/NUSspli#84]
- error al instalar el 20% de los juegos
- imagen de las carátulas en lista de descarga 
- poder descargar varios juegos en cola 
- descargas en segundo plano mientras juegas o usas wii u
- mejorar diseño de la interfaz
- juegos no eshop como call of duty ......etc

**Comment by V10lator** [comment]
Can't understand a single word!

**Comment by luismyru** [comment]
- Error al instalar juegos 
- Podría salir la portada del juego elegido al seleccionarlo 
- poder salir de la tienda y juegar con tu wii u mientras sigue descargando en segúndo plano 
- mejorar la interfaz de la tienda 
- poder descargar juegos que no estén en la eshop como calle of duty

**Comment by V10lator** [comment]
@luismyru Again: Can't help if i can't understand what you say. So write in english, please.

**Comment by Korozin** [comment]
> @luismyru Again: Can't help if i can't understand what you say. So write in english, please.

Basically they're asking for improvements. They also had an error installing games which as far as I can tell if just a duplicate at this point. The suggestions they want is the boxart of the game when you select it, being able to leave the app while it installs, improve the GUI and add games not on NUS like CoD: Bo2. Basically all low priority things since the program seems fine to me as is,

Some of the things they're asking for like downloading in the background would be considered "unsafe" to some anyways since you'd actually have to hook the app into a system application and you know people would mess up that process. Secondly I don't think they realize that it isnt really possible to add games like Bo2 on it since it was a disc only title meaning it's existence is nowhere on the NUS servers and the only feasible way to get it would be getting a disc dump which lets face it is sketchy at least.

Anyways have a good day and thank you for your amazing work.
